// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TutorConnect.API.Data;

#nullable disable

namespace TutorConnect.API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260414170457_AddIteration2AcademicAndTutorData")]
    partial class AddIteration2AcademicAndTutorData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TutorConnect.API.Models.Assignment", b =>
                {
                    b.Property<int>("Assignment_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Assignment_ID"));

                    b.Property<DateTime>("Assignment_Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Assignment_Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Module_Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Module_Code1")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Assignment_ID");

                    b.HasIndex("Module_Code1");

                    b.ToTable("Assignments");
                });

            modelBuilder.Entity("TutorConnect.API.Models.Assignment_Submission", b =>
                {
                    b.Property<int>("Assignment_Submission_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Assignment_Submission_ID"));

                    b.Property<string>("Assignment_Feedback")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Assignment_ID")
                        .HasColumnType("int");

                    b.Property<int?>("Assignment_ID1")
                        .HasColumnType("int");

                    b.Property<decimal>("Assignment_grade_amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("StudentUser_ID")
                        .HasColumnType("int");

                    b.Property<int>("Student_ID")
                        .HasColumnType("int");

                    b.HasKey("Assignment_Submission_ID");

                    b.HasIndex("Assignment_ID1");

                    b.HasIndex("StudentUser_ID");

                    b.ToTable("Assignment_Submissions");
                });

            modelBuilder.Entity("TutorConnect.API.Models.Log_Hours", b =>
                {
                    b.Property<int>("Log_Hours_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Log_Hours_ID"));

                    b.Property<decimal>("Log_Hours_Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateOnly>("Log_Hours_Date")
                        .HasColumnType("date");

                    b.Property<TimeOnly>("Log_Hours_Time")
                        .HasColumnType("time");

                    b.Property<int?>("TutorUser_ID")
                        .HasColumnType("int");

                    b.Property<int>("Tutor_ID")
                        .HasColumnType("int");

                    b.HasKey("Log_Hours_ID");

                    b.HasIndex("TutorUser_ID");

                    b.ToTable("Log_Hours");
                });

            modelBuilder.Entity("TutorConnect.API.Models.Module", b =>
                {
                    b.Property<string>("Module_Code")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Module_Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Module_Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Module_Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Module_Code");

                    b.ToTable("Modules");
                });

            modelBuilder.Entity("TutorConnect.API.Models.Module_Resource", b =>
                {
                    b.Property<int>("Module_Resource_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Module_Resource_ID"));

                    b.Property<string>("Module_Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Module_Code1")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Module_Resource_Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Module_Resource_Type_ID")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Module_Resource_ID");

                    b.HasIndex("Module_Code1");

                    b.ToTable("Module_Resources");
                });

            modelBuilder.Entity("TutorConnect.API.Models.Quiz", b =>
                {
                    b.Property<int>("Quiz_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Quiz_ID"));

                    b.Property<TimeSpan>("End_Time")
                        .HasColumnType("time");

                    b.Property<string>("Module_Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Module_Code1")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("Quiz_Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Quiz_Details")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Quiz_Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<TimeSpan>("Start_Time")
                        .HasColumnType("time");

                    b.HasKey("Quiz_ID");

                    b.HasIndex("Module_Code1");

                    b.ToTable("Quizzes");
                });

            modelBuilder.Entity("TutorConnect.API.Models.User", b =>
                {
                    b.Property<int>("User_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("User_ID"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("User_Role_ID")
                        .HasColumnType("int");

                    b.Property<int?>("User_Role_ID1")
                        .HasColumnType("int");

                    b.HasKey("User_ID");

                    b.HasIndex("User_Role_ID1");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("TutorConnect.API.Models.User_Role", b =>
                {
                    b.Property<int>("User_Role_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("User_Role_ID"));

                    b.Property<string>("User_Role_Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("User_Role_ID");

                    b.ToTable("User_Roles");
                });

            modelBuilder.Entity("TutorConnect.API.Models.Assignment", b =>
                {
                    b.HasOne("TutorConnect.API.Models.Module", "Module")
                        .WithMany()
                        .HasForeignKey("Module_Code1");

                    b.Navigation("Module");
                });

            modelBuilder.Entity("TutorConnect.API.Models.Assignment_Submission", b =>
                {
                    b.HasOne("TutorConnect.API.Models.Assignment", "Assignment")
                        .WithMany()
                        .HasForeignKey("Assignment_ID1");

                    b.HasOne("TutorConnect.API.Models.User", "Student")
                        .WithMany()
                        .HasForeignKey("StudentUser_ID");

                    b.Navigation("Assignment");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("TutorConnect.API.Models.Log_Hours", b =>
                {
                    b.HasOne("TutorConnect.API.Models.User", "Tutor")
                        .WithMany()
                        .HasForeignKey("TutorUser_ID");

                    b.Navigation("Tutor");
                });

            modelBuilder.Entity("TutorConnect.API.Models.Module_Resource", b =>
                {
                    b.HasOne("TutorConnect.API.Models.Module", "Module")
                        .WithMany()
                        .HasForeignKey("Module_Code1");

                    b.Navigation("Module");
                });

            modelBuilder.Entity("TutorConnect.API.Models.Quiz", b =>
                {
                    b.HasOne("TutorConnect.API.Models.Module", "Module")
                        .WithMany()
                        .HasForeignKey("Module_Code1");

                    b.Navigation("Module");
                });

            modelBuilder.Entity("TutorConnect.API.Models.User", b =>
                {
                    b.HasOne("TutorConnect.API.Models.User_Role", "User_Role")
                        .WithMany("Users")
                        .HasForeignKey("User_Role_ID1");

                    b.Navigation("User_Role");
                });

            modelBuilder.Entity("TutorConnect.API.Models.User_Role", b =>
                {
                    b.Navigation("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
