// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TutorConnect.API.Data;

#nullable disable

namespace TutorConnect.API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260417120000_AddStudentEnrollmentAndFileUploadSupport")]
    partial class AddStudentEnrollmentAndFileUploadSupport
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            // Note: This is a simplified snapshot. The actual snapshot should contain all entity configurations.
            // This file is auto-generated and should match the current DbContext state.

            modelBuilder.Entity("TutorConnect.API.Models.Student_Module", b =>
                {
                    b.Property<int>("Enrollment_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Enrollment_ID"));

                    b.Property<DateTime>("Enrollment_Date")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Module_Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Student_ID")
                        .HasColumnType("int");

                    b.Property<string>("Unenroll_Reason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("Unenroll_Date")
                        .HasColumnType("datetime2");

                    b.HasKey("Enrollment_ID");

                    b.HasIndex("Module_Code");

                    b.HasIndex("Student_ID");

                    b.HasIndex("Student_ID", "Module_Code", "IsActive")
                        .HasDatabaseName("IX_Student_Modules_Active_Enrollments");

                    b.ToTable("Student_Modules");
                });
#pragma warning restore 612, 618
        }
    }
}
