// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TutorConnect.API.Data;

#nullable disable

namespace TutorConnect.API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260429221126_QuizRedesign")]
    partial class QuizRedesign
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TutorConnect.API.Models.Announcement", b =>
                {
                    b.Property<int>("Announcement_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Announcement_ID"));

                    b.Property<int?>("Admin_ID")
                        .HasColumnType("int");

                    b.Property<string>("Announcement_Details")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Announcement_Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Announcement_Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Date_Posted")
                        .HasColumnType("datetime2");

                    b.Property<string>("Module_Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Tutor_ID")
                        .HasColumnType("int");

                    b.HasKey("Announcement_ID");

                    b.ToTable("Announcements");
                });

            modelBuilder.Entity("TutorConnect.API.Models.Assignment", b =>
                {
                    b.Property<int>("Assignment_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Assignment_ID"));

                    b.Property<DateTime>("Assignment_Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Assignment_Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Module_Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Module_Code1")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Assignment_ID");

                    b.HasIndex("Module_Code1");

                    b.ToTable("Assignments");
                });

            modelBuilder.Entity("TutorConnect.API.Models.Assignment_Submission", b =>
                {
                    b.Property<int>("Submission_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Submission_ID"));

                    b.Property<int>("Assignment_ID")
                        .HasColumnType("int");

                    b.Property<string>("Feedback")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("Feedback_Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("File_Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("File_Path")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("File_Size")
                        .HasColumnType("bigint");

                    b.Property<string>("File_Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("Grade")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("Graded_By")
                        .HasColumnType("int");

                    b.Property<int>("Student_ID")
                        .HasColumnType("int");

                    b.Property<DateTime>("Submission_Date")
                        .HasColumnType("datetime2");

                    b.HasKey("Submission_ID");

                    b.HasIndex("Assignment_ID");

                    b.HasIndex("Student_ID");

                    b.ToTable("Assignment_Submissions");
                });

            modelBuilder.Entity("TutorConnect.API.Models.Attendance_Status", b =>
                {
                    b.Property<int>("Attendance_Status_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Attendance_Status_ID"));

                    b.Property<string>("Status_Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Attendance_Status_ID");

                    b.ToTable("Attendance_Statuses");
                });

            modelBuilder.Entity("TutorConnect.API.Models.Audit_Log", b =>
                {
                    b.Property<int>("Audit_Log_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Audit_Log_ID"));

                    b.Property<DateOnly>("Audit_Date")
                        .HasColumnType("date");

                    b.Property<TimeOnly>("Audit_Time")
                        .HasColumnType("time");

                    b.Property<string>("Critical_Data")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Transaction_Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("User_ID")
                        .HasColumnType("int");

                    b.HasKey("Audit_Log_ID");

                    b.ToTable("Audit_Logs");
                });

            modelBuilder.Entity("TutorConnect.API.Models.Booking", b =>
                {
                    b.Property<int>("Booking_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Booking_ID"));

                    b.Property<int>("Booking_Slot_ID")
                        .HasColumnType("int");

                    b.Property<int?>("StudentUser_ID")
                        .HasColumnType("int");

                    b.Property<int>("Student_ID")
                        .HasColumnType("int");

                    b.HasKey("Booking_ID");

                    b.HasIndex("Booking_Slot_ID");

                    b.HasIndex("StudentUser_ID");

                    b.ToTable("Bookings");
                });

            modelBuilder.Entity("TutorConnect.API.Models.Booking_Slot", b =>
                {
                    b.Property<int>("Booking_Slot_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Booking_Slot_ID"));

                    b.Property<bool>("Is_Booked")
                        .HasColumnType("bit");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Max_Capacity")
                        .HasColumnType("int");

                    b.Property<string>("Module_Code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Session_Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly>("Slot_Date")
                        .HasColumnType("date");

                    b.Property<TimeOnly>("Slot_Time")
                        .HasColumnType("time");

                    b.Property<int>("Tutor_ID")
                        .HasColumnType("int");

                    b.HasKey("Booking_Slot_ID");

                    b.HasIndex("Tutor_ID");

                    b.ToTable("Booking_Slots");
                });

            modelBuilder.Entity("TutorConnect.API.Models.Business_Rule", b =>
                {
                    b.Property<int>("Rule_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Rule_ID"));

                    b.Property<string>("Rule_Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Rule_Value")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Rule_ID");

                    b.ToTable("Business_Rules");
                });

            modelBuilder.Entity("TutorConnect.API.Models.FAQ", b =>
                {
                    b.Property<int>("FAQ_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FAQ_ID"));

                    b.Property<string>("Answer")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("FAQ_Category_ID")
                        .HasColumnType("int");

                    b.Property<string>("Question")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("FAQ_ID");

                    b.ToTable("FAQs");
                });

            modelBuilder.Entity("TutorConnect.API.Models.FAQ_Category", b =>
                {
                    b.Property<int>("FAQ_Category_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FAQ_Category_ID"));

                    b.Property<string>("Category_Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("FAQ_Category_ID");

                    b.ToTable("FAQ_Categories");
                });

            modelBuilder.Entity("TutorConnect.API.Models.Help_Page", b =>
                {
                    b.Property<int>("Help_Page_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Help_Page_ID"));

                    b.Property<string>("Help_Page_Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Help_Page_Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Help_Page_ID");

                    b.ToTable("Help_Pages");
                });

            modelBuilder.Entity("TutorConnect.API.Models.Help_Resource", b =>
                {
                    b.Property<int>("Help_Video_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Help_Video_ID"));

                    b.Property<string>("Video_Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Video_URL")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Help_Video_ID");

                    b.ToTable("Help_Resources");
                });

            modelBuilder.Entity("TutorConnect.API.Models.Log_Hours", b =>
                {
                    b.Property<int>("Log_Hours_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Log_Hours_ID"));

                    b.Property<DateTime?>("ApprovalDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ApprovedBy_Admin_ID")
                        .HasColumnType("int");

                    b.Property<bool>("IsApproved")
                        .HasColumnType("bit");

                    b.Property<decimal>("Log_Hours_Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateOnly>("Log_Hours_Date")
                        .HasColumnType("date");

                    b.Property<TimeOnly>("Log_Hours_Time")
                        .HasColumnType("time");

                    b.Property<int>("Tutor_ID")
                        .HasColumnType("int");

                    b.HasKey("Log_Hours_ID");

                    b.HasIndex("Tutor_ID");

                    b.ToTable("Log_Hours");
                });

            modelBuilder.Entity("TutorConnect.API.Models.Media_Content", b =>
                {
                    b.Property<int>("Media_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Media_ID"));

                    b.Property<string>("Media_Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Media_Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Media_ID");

                    b.ToTable("Media_Contents");
                });

            modelBuilder.Entity("TutorConnect.API.Models.Module", b =>
                {
                    b.Property<string>("Module_Code")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Module_Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Module_Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Module_Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Module_Code");

                    b.ToTable("Modules");
                });

            modelBuilder.Entity("TutorConnect.API.Models.Module_Resource", b =>
                {
                    b.Property<int>("Module_Resource_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Module_Resource_ID"));

                    b.Property<DateTime>("Date_Added")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Folder_Is_Visible")
                        .HasColumnType("bit");

                    b.Property<string>("Folder_Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Is_Visible")
                        .HasColumnType("bit");

                    b.Property<string>("Module_Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Module_Code1")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Module_Resource_Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Module_Resource_Type_ID")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Resource_URL")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Module_Resource_ID");

                    b.HasIndex("Module_Code1");

                    b.ToTable("Module_Resources");
                });

            modelBuilder.Entity("TutorConnect.API.Models.Module_Wishlist", b =>
                {
                    b.Property<int>("Wishlist_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Wishlist_ID"));

                    b.Property<DateTime>("Date_Submitted")
                        .HasColumnType("datetime2");

                    b.Property<string>("Module_Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Module_Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Student_ID")
                        .HasColumnType("int");

                    b.HasKey("Wishlist_ID");

                    b.ToTable("Module_Wishlists");
                });

            modelBuilder.Entity("TutorConnect.API.Models.Notification", b =>
                {
                    b.Property<int>("Notification_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Notification_ID"));

                    b.Property<DateTime>("Date_Sent")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Is_Read")
                        .HasColumnType("bit");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("User_ID")
                        .HasColumnType("int");

                    b.Property<int?>("User_ID1")
                        .HasColumnType("int");

                    b.HasKey("Notification_ID");

                    b.HasIndex("User_ID1");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("TutorConnect.API.Models.Payment", b =>
                {
                    b.Property<int>("Payment_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Payment_ID"));

                    b.Property<string>("Account_Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Account_Number")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Bank")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Branch_Code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Module_Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Module_Code1")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("Payment_Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Payment_Reference")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Payment_Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("StudentUser_ID")
                        .HasColumnType("int");

                    b.Property<int>("Student_ID")
                        .HasColumnType("int");

                    b.HasKey("Payment_ID");

                    b.HasIndex("Module_Code1");

                    b.HasIndex("StudentUser_ID");

                    b.ToTable("Payments");
                });

            modelBuilder.Entity("TutorConnect.API.Models.Quiz", b =>
                {
                    b.Property<int>("Quiz_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Quiz_ID"));

                    b.Property<bool>("Is_Visible")
                        .HasColumnType("bit");

                    b.Property<string>("Module_Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Module_Code1")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("Quiz_Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Quiz_Details")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Quiz_Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Quiz_ID");

                    b.HasIndex("Module_Code1");

                    b.ToTable("Quizzes");
                });

            modelBuilder.Entity("TutorConnect.API.Models.Quiz_Question", b =>
                {
                    b.Property<int>("Question_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Question_ID"));

                    b.Property<int>("Question_Order")
                        .HasColumnType("int");

                    b.Property<string>("Question_Text")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Quiz_ID")
                        .HasColumnType("int");

                    b.HasKey("Question_ID");

                    b.ToTable("Quiz_Questions");
                });

            modelBuilder.Entity("TutorConnect.API.Models.Quiz_Question_Option", b =>
                {
                    b.Property<int>("Option_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Option_ID"));

                    b.Property<bool>("Is_Correct")
                        .HasColumnType("bit");

                    b.Property<string>("Option_Text")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Question_ID")
                        .HasColumnType("int");

                    b.HasKey("Option_ID");

                    b.ToTable("Quiz_Question_Options");
                });

            modelBuilder.Entity("TutorConnect.API.Models.Recorded_Session", b =>
                {
                    b.Property<int>("Recording_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Recording_ID"));

                    b.Property<string>("Module_Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Recording_Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Recording_Filesize")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Recording_Filetype")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Recording_Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Session_ID")
                        .HasColumnType("int");

                    b.HasKey("Recording_ID");

                    b.ToTable("Recorded_Sessions");
                });

            modelBuilder.Entity("TutorConnect.API.Models.Resource_Type", b =>
                {
                    b.Property<int>("Resource_Type_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Resource_Type_ID"));

                    b.Property<string>("Type_Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Resource_Type_ID");

                    b.ToTable("Resource_Types");
                });

            modelBuilder.Entity("TutorConnect.API.Models.Session_Attendance", b =>
                {
                    b.Property<int>("Session_Attendance_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Session_Attendance_ID"));

                    b.Property<int>("Attendance_Status_ID")
                        .HasColumnType("int");

                    b.Property<int?>("Attendance_Status_ID1")
                        .HasColumnType("int");

                    b.Property<string>("Session_Attendance_Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Session_ID")
                        .HasColumnType("int");

                    b.Property<int>("Student_ID")
                        .HasColumnType("int");

                    b.HasKey("Session_Attendance_ID");

                    b.HasIndex("Attendance_Status_ID1");

                    b.ToTable("Session_Attendances");
                });

            modelBuilder.Entity("TutorConnect.API.Models.Session_Review", b =>
                {
                    b.Property<int>("Session_Review_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Session_Review_ID"));

                    b.Property<string>("Session_Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Session_ID")
                        .HasColumnType("int");

                    b.Property<int>("Session_Rating")
                        .HasColumnType("int");

                    b.Property<int>("Student_ID")
                        .HasColumnType("int");

                    b.HasKey("Session_Review_ID");

                    b.ToTable("Session_Reviews");
                });

            modelBuilder.Entity("TutorConnect.API.Models.Student_Group", b =>
                {
                    b.Property<int>("Student_Group_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Student_Group_ID"));

                    b.Property<string>("Group_Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Student_Group_ID");

                    b.ToTable("Student_Groups");
                });

            modelBuilder.Entity("TutorConnect.API.Models.Student_Group_Allocation", b =>
                {
                    b.Property<int>("Allocation_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Allocation_ID"));

                    b.Property<int>("Student_Group_ID")
                        .HasColumnType("int");

                    b.Property<int?>("Student_Group_ID1")
                        .HasColumnType("int");

                    b.Property<int>("Student_ID")
                        .HasColumnType("int");

                    b.HasKey("Allocation_ID");

                    b.HasIndex("Student_Group_ID1");

                    b.ToTable("Student_Group_Allocations");
                });

            modelBuilder.Entity("TutorConnect.API.Models.Student_Module", b =>
                {
                    b.Property<int>("Enrollment_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Enrollment_ID"));

                    b.Property<DateTime>("Enrollment_Date")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Module_Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Student_ID")
                        .HasColumnType("int");

                    b.Property<DateTime?>("Unenroll_Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Unenroll_Reason")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Enrollment_ID");

                    b.HasIndex("Module_Code");

                    b.HasIndex("Student_ID");

                    b.ToTable("Student_Modules");
                });

            modelBuilder.Entity("TutorConnect.API.Models.Student_Quiz", b =>
                {
                    b.Property<int>("Student_Quiz_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Student_Quiz_ID"));

                    b.Property<DateTime?>("End_Time")
                        .HasColumnType("datetime2");

                    b.Property<int>("Quiz_ID")
                        .HasColumnType("int");

                    b.Property<int?>("Quiz_ID1")
                        .HasColumnType("int");

                    b.Property<decimal>("Quiz_Score")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("Start_Time")
                        .HasColumnType("datetime2");

                    b.Property<int>("Student_ID")
                        .HasColumnType("int");

                    b.Property<DateTime>("Submission_Date")
                        .HasColumnType("datetime2");

                    b.HasKey("Student_Quiz_ID");

                    b.HasIndex("Quiz_ID1");

                    b.ToTable("Student_Quizzes");
                });

            modelBuilder.Entity("TutorConnect.API.Models.Student_Quiz_Answer", b =>
                {
                    b.Property<int>("Answer_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Answer_ID"));

                    b.Property<int>("Option_ID")
                        .HasColumnType("int");

                    b.Property<int>("Question_ID")
                        .HasColumnType("int");

                    b.Property<int>("Student_Quiz_ID")
                        .HasColumnType("int");

                    b.HasKey("Answer_ID");

                    b.ToTable("Student_Quiz_Answers");
                });

            modelBuilder.Entity("TutorConnect.API.Models.Testimonial", b =>
                {
                    b.Property<int>("Testimonial_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Testimonial_ID"));

                    b.Property<bool>("IsApproved")
                        .HasColumnType("bit");

                    b.Property<int>("Student_ID")
                        .HasColumnType("int");

                    b.Property<int>("Testimonial_Category_ID")
                        .HasColumnType("int");

                    b.Property<string>("Testimonial_Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Testimonial_ID");

                    b.ToTable("Testimonials");
                });

            modelBuilder.Entity("TutorConnect.API.Models.Testimonial_Category", b =>
                {
                    b.Property<int>("Testimonial_Category_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Testimonial_Category_ID"));

                    b.Property<string>("Test_Category_Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Testimonial_Category_ID");

                    b.ToTable("Testimonial_Categories");
                });

            modelBuilder.Entity("TutorConnect.API.Models.Tutor_Module", b =>
                {
                    b.Property<int>("Tutor_Module_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Tutor_Module_ID"));

                    b.Property<DateTime>("Assigned_Date")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Module_Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Tutor_ID")
                        .HasColumnType("int");

                    b.HasKey("Tutor_Module_ID");

                    b.HasIndex("Module_Code");

                    b.HasIndex("Tutor_ID");

                    b.ToTable("Tutor_Modules");
                });

            modelBuilder.Entity("TutorConnect.API.Models.Tutor_Review", b =>
                {
                    b.Property<int>("Tutor_Review_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Tutor_Review_ID"));

                    b.Property<int>("Student_ID")
                        .HasColumnType("int");

                    b.Property<int>("Tutor_ID")
                        .HasColumnType("int");

                    b.Property<int>("Tutor_Rating")
                        .HasColumnType("int");

                    b.HasKey("Tutor_Review_ID");

                    b.ToTable("Tutor_Reviews");
                });

            modelBuilder.Entity("TutorConnect.API.Models.User", b =>
                {
                    b.Property<int>("User_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("User_ID"));

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Bio")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordResetCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("PasswordResetCodeExpiration")
                        .HasColumnType("datetime2");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("User_Role_ID")
                        .HasColumnType("int");

                    b.HasKey("User_ID");

                    b.HasIndex("User_Role_ID");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("TutorConnect.API.Models.User_Role", b =>
                {
                    b.Property<int>("User_Role_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("User_Role_ID"));

                    b.Property<string>("User_Role_Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("User_Role_ID");

                    b.ToTable("User_Roles");
                });

            modelBuilder.Entity("TutorConnect.API.Models.Assignment", b =>
                {
                    b.HasOne("TutorConnect.API.Models.Module", "Module")
                        .WithMany()
                        .HasForeignKey("Module_Code1");

                    b.Navigation("Module");
                });

            modelBuilder.Entity("TutorConnect.API.Models.Assignment_Submission", b =>
                {
                    b.HasOne("TutorConnect.API.Models.Assignment", "Assignment")
                        .WithMany()
                        .HasForeignKey("Assignment_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TutorConnect.API.Models.User", "Student")
                        .WithMany()
                        .HasForeignKey("Student_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Assignment");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("TutorConnect.API.Models.Booking", b =>
                {
                    b.HasOne("TutorConnect.API.Models.Booking_Slot", "Booking_Slot")
                        .WithMany()
                        .HasForeignKey("Booking_Slot_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TutorConnect.API.Models.User", "Student")
                        .WithMany()
                        .HasForeignKey("StudentUser_ID");

                    b.Navigation("Booking_Slot");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("TutorConnect.API.Models.Booking_Slot", b =>
                {
                    b.HasOne("TutorConnect.API.Models.User", "Tutor")
                        .WithMany()
                        .HasForeignKey("Tutor_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tutor");
                });

            modelBuilder.Entity("TutorConnect.API.Models.Log_Hours", b =>
                {
                    b.HasOne("TutorConnect.API.Models.User", "Tutor")
                        .WithMany()
                        .HasForeignKey("Tutor_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tutor");
                });

            modelBuilder.Entity("TutorConnect.API.Models.Module_Resource", b =>
                {
                    b.HasOne("TutorConnect.API.Models.Module", "Module")
                        .WithMany()
                        .HasForeignKey("Module_Code1");

                    b.Navigation("Module");
                });

            modelBuilder.Entity("TutorConnect.API.Models.Notification", b =>
                {
                    b.HasOne("TutorConnect.API.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("User_ID1");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TutorConnect.API.Models.Payment", b =>
                {
                    b.HasOne("TutorConnect.API.Models.Module", "Module")
                        .WithMany()
                        .HasForeignKey("Module_Code1");

                    b.HasOne("TutorConnect.API.Models.User", "Student")
                        .WithMany()
                        .HasForeignKey("StudentUser_ID");

                    b.Navigation("Module");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("TutorConnect.API.Models.Quiz", b =>
                {
                    b.HasOne("TutorConnect.API.Models.Module", "Module")
                        .WithMany()
                        .HasForeignKey("Module_Code1");

                    b.Navigation("Module");
                });

            modelBuilder.Entity("TutorConnect.API.Models.Session_Attendance", b =>
                {
                    b.HasOne("TutorConnect.API.Models.Attendance_Status", "Attendance_Status")
                        .WithMany()
                        .HasForeignKey("Attendance_Status_ID1");

                    b.Navigation("Attendance_Status");
                });

            modelBuilder.Entity("TutorConnect.API.Models.Student_Group_Allocation", b =>
                {
                    b.HasOne("TutorConnect.API.Models.Student_Group", "Student_Group")
                        .WithMany()
                        .HasForeignKey("Student_Group_ID1");

                    b.Navigation("Student_Group");
                });

            modelBuilder.Entity("TutorConnect.API.Models.Student_Module", b =>
                {
                    b.HasOne("TutorConnect.API.Models.Module", "Module")
                        .WithMany()
                        .HasForeignKey("Module_Code")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TutorConnect.API.Models.User", "Student")
                        .WithMany()
                        .HasForeignKey("Student_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Module");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("TutorConnect.API.Models.Student_Quiz", b =>
                {
                    b.HasOne("TutorConnect.API.Models.Quiz", "Quiz")
                        .WithMany()
                        .HasForeignKey("Quiz_ID1");

                    b.Navigation("Quiz");
                });

            modelBuilder.Entity("TutorConnect.API.Models.Tutor_Module", b =>
                {
                    b.HasOne("TutorConnect.API.Models.Module", "Module")
                        .WithMany()
                        .HasForeignKey("Module_Code")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TutorConnect.API.Models.User", "Tutor")
                        .WithMany()
                        .HasForeignKey("Tutor_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Module");

                    b.Navigation("Tutor");
                });

            modelBuilder.Entity("TutorConnect.API.Models.User", b =>
                {
                    b.HasOne("TutorConnect.API.Models.User_Role", "User_Role")
                        .WithMany("Users")
                        .HasForeignKey("User_Role_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User_Role");
                });

            modelBuilder.Entity("TutorConnect.API.Models.User_Role", b =>
                {
                    b.Navigation("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
