// Iteration 6: UC 6.x (Reports) — no new models required; reports query existing data from Iterations 4 and 5

namespace TutorConnect.API.Models
{
    // No new model classes for Iteration 6.
    // Reports are generated by querying models defined in Iteration4Models.cs and Iteration5Models.cs.
}
